
const course = [
    {
        id: 0,
        courseTitle : "Summer Art Camp! 5 Days of Artists and Painting Monet,Van Gogh, Matisse , & More",
        singleDay : false,
        description: "In this 5 day class we will explore artists Monet, Matisse, Van Gogh, among others and then recreate paintings using crayon and watercolor. Students will have fun learning about the artists & creating their own art inspired by their work.",
        author : "Kimberley R Moseler",
        authorImg: "/assets/profile.jpeg",
        teacherReviews: 467,
        classReviews: 5,
        completedBy: 21,
        courseImg: "/assets/download.jpeg",
        courseRating : 4,
        teacherRating: 5
    },
    {
        id: 1,
        courseTitle : "A complete Next JS Bootcamp with Tailwind",
        singleDay : false,
        description: "In this 5 day class we will explore artists Monet, Matisse, Van Gogh, among others and then recreate paintings using crayon and watercolor. Students will have fun learning about the artists & creating their own art inspired by their work.",
        author : "Kimberley R Moseler",
        authorImg: "/assets/profile.jpeg",
        teacherReviews: 467,
        classReviews: 5,
        completedBy: 21,
        courseImg: "/assets/next.webp",
        courseRating : 4,
        teacherRating: 5
    },
    {
        id: 2,
        courseTitle : "Learn Python: The Complete Python Programming Course",
        singleDay : false,
        description: "In this 5 day class we will explore artists Monet, Matisse, Van Gogh, among others and then recreate paintings using crayon and watercolor. Students will have fun learning about the artists & creating their own art inspired by their work.",
        author : "Kimberley R Moseler",
        authorImg: "/assets/profile.jpeg",
        teacherReviews: 467,
        classReviews: 5,
        completedBy: 21,
        courseImg: "/assets/python.webp",
        courseRating : 4,
        teacherRating: 5
    },
    {
        id: 3,
        courseTitle : "100 Days of Code: The complete Javascript guide ",
        singleDay : false,
        description: "In this 5 day class we will explore artists Monet, Matisse, Van Gogh, among others and then recreate paintings using crayon and watercolor. Students will have fun learning about the artists & creating their own art inspired by their work.",
        author : "Kimberley R Moseler",
        authorImg: "/assets/profile.jpeg",
        teacherReviews: 467,
        classReviews: 5,
        completedBy: 21,
        courseImg: "/assets/javascript.webp",
        courseRating : 4,
        teacherRating: 5
    },
    {
        id: 4,
        courseTitle : "The Complete 2022 Web Development Bootcamp by Dr. Angela Yu",
        singleDay : false,
        description: "In this 5 day class we will explore artists Monet, Matisse, Van Gogh, among others and then recreate paintings using crayon and watercolor. Students will have fun learning about the artists & creating their own art inspired by their work.",
        author : "Kimberley R Moseler",
        authorImg: "/assets/profile.jpeg",
        teacherReviews: 467,
        classReviews: 5,
        completedBy: 21,
        courseImg: "/assets/download.jpeg",
        courseRating : 4,
        teacherRating: 5
    },
    {
        id: 5,
        courseTitle : "Summer Art Camp! 5 Days of Artists and Painting Monet,Van Gogh, Matisse , & More",
        singleDay : false,
        description: "In this 5 day class we will explore artists Monet, Matisse, Van Gogh, among others and then recreate paintings using crayon and watercolor. Students will have fun learning about the artists & creating their own art inspired by their work.",
        author : "Kimberley R Moseler",
        authorImg: "/assets/profile.jpeg",
        teacherReviews: 467,
        classReviews: 5,
        completedBy: 21,
        courseImg: "/assets/download.jpeg",
        courseRating : 4,
        teacherRating: 5
    },
    {
        id: 6,
        courseTitle : "Summer Art Camp! 5 Days of Artists and Painting Monet,Van Gogh, Matisse , & More",
        singleDay : false,
        description: "In this 5 day class we will explore artists Monet, Matisse, Van Gogh, among others and then recreate paintings using crayon and watercolor. Students will have fun learning about the artists & creating their own art inspired by their work.",
        author : "Kimberley R Moseler",
        authorImg: "/assets/profile.jpeg",
        teacherReviews: 467,
        classReviews: 5,
        completedBy: 21,
        courseImg: "/assets/download.jpeg",
        courseRating : 4,
        teacherRating: 5
    },
    {
        id: 7,
        courseTitle : "Summer Art Camp! 5 Days of Artists and Painting Monet,Van Gogh, Matisse , & More",
        singleDay : false,
        description: "In this 5 day class we will explore artists Monet, Matisse, Van Gogh, among others and then recreate paintings using crayon and watercolor. Students will have fun learning about the artists & creating their own art inspired by their work.",
        author : "Kimberley R Moseler",
        authorImg: "/assets/profile.jpeg",
        teacherReviews: 467,
        classReviews: 5,
        completedBy: 21,
        courseImg: "/assets/download.jpeg",
        courseRating : 4,
        teacherRating: 5
    },
    {
        id: 8,
        courseTitle : "Summer Art Camp! 5 Days of Artists and Painting Monet,Van Gogh, Matisse , & More",
        singleDay : false,
        description: "In this 5 day class we will explore artists Monet, Matisse, Van Gogh, among others and then recreate paintings using crayon and watercolor. Students will have fun learning about the artists & creating their own art inspired by their work.",
        author : "Kimberley R Moseler",
        authorImg: "/assets/profile.jpeg",
        teacherReviews: 467,
        classReviews: 5,
        completedBy: 21,
        courseImg: "/assets/download.jpeg",
        courseRating : 4,
        teacherRating: 5
    },
]

export default course;